server:
  port: 9001
  servlet:
    context-path: /auth

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/piggy_bank_local
    username: root
    password: Accion@10
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 59630c22c327a440f4dc
            client-secret: f5556ff498d1b7743e762a1cdea47ed8869f6a9b