server:
  port: 8001
  servlet:
    context-path: /auth

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/piggy_bank_local
    username: root
    password: Accion@10
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml