server:
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/project_phonebook
    username: root
    password: Accion@10
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

app:
  service:
    authenticate-user: true
    validate-user: true
    authorise:
      authorise-user: true