server:
  port: 8000
  servlet:
    context-path: /user

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/project_phonebook_prod
    username: root
    password: Accion@10
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

app:
  service:
    allow-user-creation: false
    validate-user: true
    authorise:
      authorise-user: true